### ISSUE TITLE
Share with Friends should open in new tab 

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/norfolkcounts#32]
Sorry, I didn't realise this whilst we were chatting or I would have brought it up then. This is actually a new feature - opening in a new tab doesn't happen on the Leeds Counts site, and that's because of the way the Facebook sharing modal works. It's not something we'll be able to add in within the scope of this project I'm afraid. Do feel free to ask any questions you'd like here, but if you don't have any, please close the issue 😃

**Comment by gabrieldavalos** [comment]
Nope. We understand. Thanks!
