### ISSUE TITLE
Keyboard appears with modals (on mobile)

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/norfolkcounts#38]
"When clicking on the About Us section and ‘How do we know Norfolk’s impact?’ section, the keyboard pops up making it difficult to see everything."

@aaronparr we haven't been able to replicate this - can you check and see if it's still an issue for you?

**Comment by gabrieldavalos** [comment]
We're checking now

**Comment by gabrieldavalos** [comment]
Still nobody was able to replicate. We'll do another round tomorrow and see if it comes up again.
