### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by lucymk** [InFact-coop/norfolkcounts#40]
- Change references from 'this year' to 'last year'
- ~~Small CTA on action page change to: ‘Ask Local MP and Chief Secretary to the Treasury Liz Truss to protect Norfolk’s aid contributions.’~~

Is the latter still needed if we are getting rid of that CTA?

**Comment by gabrieldavalos** [comment]
Nope. If it related to the first, smaller CTA then we can scrap it.

**Comment by gabrieldavalos** [comment]
Ok, I think we've made all the changes in word press. Are there any others on your end?

**Comment by lucymk** [comment]
@gabrieldavalos amazing, you know I just searched the codebase and there doesn't seem to be. Maybe we should leave this issue open for now though, in case other copy changes come in that I need to do.

**Comment by gabrieldavalos** [comment]
Sounds good!
